// <auto-generated />
using CurrencyConvert;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CurrencyConvert.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20220102142208_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("CurrencyConvert.Entities.Currency", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("rate")
                        .HasColumnType("REAL");

                    b.Property<string>("targetCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("targetName")
                        .HasColumnType("TEXT");

                    b.Property<string>("updateDate")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("CurrencyConvert.Entities.Log", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("baseName")
                        .HasColumnType("TEXT");

                    b.Property<double>("result")
                        .HasColumnType("REAL");

                    b.Property<string>("targetName")
                        .HasColumnType("TEXT");

                    b.Property<double>("value")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("CurrencyConvert.Entities.Setting", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isFirstTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("url")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Setting");
                });
#pragma warning restore 612, 618
        }
    }
}
